### ISSUE TITLE
variables say they're not set, but they are in the env

### ISSUE THREAD

**Issue by alibama** [ezpaarse-project/ezmesure#92]
I'm getting these errors - 

:/home/ubuntu/ezmesure# docker-compose up -d --force-recreate front
WARNING: The ELASTICSEARCH_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The EZMESURE_ES_MEM_LIMIT variable is not set. Defaulting to a blank string.
WARNING: The KIBANA_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The EZMESURE_DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The SERVER_BASEPATH variable is not set. Defaulting to a blank string.
WARNING: The ELASTICSEARCH_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The EZMESURE_SMTP_HOST variable is not set. Defaulting to a blank string.
WARNING: The EZMESURE_SMTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The EZMESURE_SMTP_SECURE variable is not set. Defaulting to a blank string.
WARNING: The EZMESURE_SMTP_IGNORE_TLS variable is not set. Defaulting to a blank string.
WARNING: The EZMESURE_SMTP_REJECT_UNAUTHORIZED variable is not set. Defaulting to a blank string.

but ezmesure.local.env.sh has most of those variables in it.... i'm confused

export EZMESURE_DOMAIN="stats.hsl.virginia.edu"
export APPLI_APACHE_SERVERADMIN="anson@virginia.edu"
export EZMESURE_DISABLE_SHIBBOLETH="true"

export EZMESURE_AUTH_SECRET="*******"
export EZMESURE_ENCRYPTION_SECRET="*****"

export ELASTICSEARCH_USERNAME="*****"
export ELASTICSEARCH_PASSWORD="******"
export EZMESURE_SMTP_HOST="127.0.0.1"

export EZMESURE_ES_MEM_LIMIT="2g"
export ES_JAVA_OPTS="-Xms2g -Xmx2g"

export EZMESURE_NODES=""
export EZMESURE_ES_NODE_MASTER="true"
export EZMESURE_ES_NODE_DATA="true"
export EZMESURE_ES_NODE_INGEST="true"
export EZMESURE_ES_NODE_SEARCH_REMOTE="true"

export EZMESURE_NOTIFICATIONS_SENDER="***@virginia.edu"
export EZMESURE_NOTIFICATIONS_RECIPIENTS="****@virginia.edu"
export EZMESURE_NOTIFICATIONS_CRON="****@virginia.edu"
export REPORTING_SENDER="****@virginia.edu"
export KIBANA_EXTERNAL_URL="https://stats.hsl.virginia.edu/kibana"

--------------------

and then the docker build crashes at the end

Building front
Sending build context to Docker daemon  3.113MB
Step 1/9 : FROM node:14.17.1-alpine3.13
 ---> 4dda2651a2fe
Step 2/9 : LABEL maintainer="ezTEAM <ezpaarse@couperin.org>"
 ---> Using cache
 ---> 01101b467c9e
Step 3/9 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> a92d32b4e29d
Step 4/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> f279fda64ef7
Step 5/9 : COPY package.json /usr/src/app/
 ---> Using cache
 ---> 8c75291dd521
Step 6/9 : RUN npm install && npm cache clean --force
 ---> Using cache
 ---> 05c303102b69
Step 7/9 : COPY . /usr/src/app
 ---> Using cache
 ---> 802fcb9c3ff2
Step 8/9 : RUN npm run build
 ---> Running in 1ad983fe38f1

> ezmesure-front@2.0.0 build /usr/src/app
> nuxt build

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:fs'
Require stack:
- /usr/src/app/node_modules/rc9/dist/index.cjs
- /usr/src/app/node_modules/@nuxt/config/dist/config.js
- /usr/src/app/node_modules/@nuxt/cli/dist/cli-index.js
- /usr/src/app/node_modules/@nuxt/cli/dist/cli.js
- /usr/src/app/node_modules/nuxt/bin/nuxt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/src/app/node_modules/rc9/dist/index.cjs:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/rc9/dist/index.cjs',
    '/usr/src/app/node_modules/@nuxt/config/dist/config.js',
    '/usr/src/app/node_modules/@nuxt/cli/dist/cli-index.js',
    '/usr/src/app/node_modules/@nuxt/cli/dist/cli.js',
    '/usr/src/app/node_modules/nuxt/bin/nuxt.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ezmesure-front@2.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ezmesure-front@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-28T19_14_59_444Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
ERROR: Service 'front' failed to build : Build failed

**Comment by tporquet** [comment]
Hello and thank you for your interest in ezMesure!
For now, we only run one instance of this service, which is our national/consortial portal on https://ezmesure.couperin.org and we plan on dedicating more time ironing out the installation steps (and associated doc) in the coming couple of months, so there can be more than this single french ezMesure instance.
Our lead developer is away for a couple of weeks for the time being. But if you are still interested by this project when we are more available, we could arrange a meeting: You can contact us directly at ezteam@couperin.org

In the meantime, have you already tested the use of ezPAARSE (the log analysis starting point for ezMesure)? Or were you only interested in the COUNTER5 (newer) aspect of ezMesure?
